### ISSUE TITLE
INTO OUTFILE?

### ISSUE THREAD

**Issue by samwilson** [Solution10/sql#2]
Is it possible to parse `SELECT ... INTO OUTFILE ...` queries?

**Comment by alexgisby** [comment]
Hey @samwilson 

Unfortunately, INTO OUTFILE is a MySQL only feature, and I'm trying to keep this library as blind to database engines as possible. The Dialects system for quoting table names etc is a necessary evil and not a habit I really want to get into!

If it's something you need, I'd encourage you to subclass the Select class and override the sql() function to inject your own fragment, something like:

``` php
class MySQLSelect extends Solution10\SQL\Select
{
    public function sql()
    {
        $candidateParts = [
            $this->buildSelectSQL(),
            $this->buildFromSQL(),
            $this->buildJoinSQL(),
            $this->buildWhereSQL($this->dialect),
            $this->buildGroupBySQL(),
            $this->buildHavingSQL($this->dialect),
            $this->buildOrderBySQL(),
            $this->buildPaginateSQL(),
            $this->buildIntoOutfileSQL()
        ];

        $realParts = [];
        foreach ($candidateParts as $p) {
            if ($p != '') {
                $realParts[] = $p;
            }
        }

        return implode(" ", $realParts);
    }
}
```

I am looking at ways of making it easier for subclasses to inject extra things into the $candidateParts array as I reckon that would make a lot of subclassers lives easier!

Thanks,
Alex

**Comment by samwilson** [comment]
Ah, that makes sense. Good idea about staying system-agnostic. Thanks! :)
